export type artifact = {
    id: number,
    name: string,
    iconUrl: string,
    rarity: 3 | 4 | 5
};

export const artifactlist: artifact[] = [
    // 5星聖遺物セット
    { id: 1, name: '剣闘士のフィナーレ', iconUrl: '/images/artifacts/gladiator-finale-icon.png', rarity: 5 },
    { id: 2, name: '大地を流浪する楽団', iconUrl: '/images/artifacts/wanderer-troupe-icon.png', rarity: 5 },
    { id: 3, name: '翠緑の影', iconUrl: '/images/artifacts/viridescent-venerer-icon.png', rarity: 5 },
    { id: 4, name: '悠久の磐岩', iconUrl: '/images/artifacts/archaic-petra-icon.png', rarity: 5 },
    { id: 5, name: '逆飛びの流星', iconUrl: '/images/artifacts/retracing-bolide-icon.png', rarity: 5 },
    { id: 6, name: '烈火を渡る賢者', iconUrl: '/images/artifacts/lavawalker-icon.png', rarity: 5 },
    { id: 7, name: '炎の魔女', iconUrl: '/images/artifacts/crimson-witch-icon.png', rarity: 5 },
    { id: 8, name: '雷のような怒り', iconUrl: '/images/artifacts/thundering-fury-icon.png', rarity: 5 },
    { id: 9, name: '雷を鎮める尊者', iconUrl: '/images/artifacts/thundersoother-icon.png', rarity: 5 },
    { id: 10, name: '氷風を彷徨う勇士', iconUrl: '/images/artifacts/blizzard-strayer-icon.png', rarity: 5 },
    { id: 11, name: '沈淪の心', iconUrl: '/images/artifacts/heart-depth-icon.png', rarity: 5 },
    { id: 12, name: '血染めの騎士道', iconUrl: '/images/artifacts/bloodstained-chivalry-icon.png', rarity: 5 },
    { id: 13, name: '旧貴族のしつけ', iconUrl: '/images/artifacts/noblesse-oblige-icon.png', rarity: 5 },
    { id: 14, name: '愛される少女', iconUrl: '/images/artifacts/maiden-beloved-icon.png', rarity: 5 },
    { id: 15, name: '千岩牢固', iconUrl: '/images/artifacts/tenacity-millelith-icon.png', rarity: 5 },
    { id: 16, name: '蒼白の炎', iconUrl: '/images/artifacts/pale-flame-icon.png', rarity: 5 },
    { id: 17, name: '追憶のしめ縄', iconUrl: '/images/artifacts/shimenawa-reminiscence-icon.png', rarity: 5 },
    { id: 18, name: '絶縁の旗印', iconUrl: '/images/artifacts/emblem-severed-fate-icon.png', rarity: 5 },
    { id: 19, name: '華館夢醒形骸記', iconUrl: '/images/artifacts/husk-opulent-dreams-icon.png', rarity: 5 },
    { id: 20, name: '海染硨磲', iconUrl: '/images/artifacts/ocean-hued-clam-icon.png', rarity: 5 },
    { id: 21, name: '辰砂往生録', iconUrl: '/images/artifacts/vermillion-hereafter-icon.png', rarity: 5 },
    { id: 22, name: '来歆の余響', iconUrl: '/images/artifacts/echoes-offering-icon.png', rarity: 5 },
    { id: 23, name: '深林の記憶', iconUrl: '/images/artifacts/deepwood-memories-icon.png', rarity: 5 },
    { id: 24, name: '金メッキの夢', iconUrl: '/images/artifacts/gilded-dreams-icon.png', rarity: 5 },
    { id: 25, name: '砂上の楼閣の史話', iconUrl: '/images/artifacts/desert-pavilion-icon.png', rarity: 5 },
    { id: 26, name: '楽園の絶花', iconUrl: '/images/artifacts/flower-paradise-lost-icon.png', rarity: 5 },
    { id: 27, name: '水仙の夢', iconUrl: '/images/artifacts/nymph-dream-icon.png', rarity: 5 },
    { id: 28, name: '花海甘露の光', iconUrl: '/images/artifacts/vourukasha-glow-icon.png', rarity: 5 },
    { id: 29, name: '黄金の劇団', iconUrl: '/images/artifacts/golden-troupe-icon.png', rarity: 5 },
    { id: 30, name: 'ファントムハンター', iconUrl: '/images/artifacts/marechaussee-hunter-icon.png', rarity: 5 },
    { id: 31, name: '昔日の宗室の儀', iconUrl: '/images/artifacts/nighttime-whispers-icon.png', rarity: 5 },
    { id: 32, name: '過ぎ去りし日の歌', iconUrl: '/images/artifacts/song-days-past-icon.png', rarity: 5 },
    { id: 33, name: '調和の奇想', iconUrl: '/images/artifacts/fragment-harmonic-whimsy-icon.png', rarity: 5 },
    { id: 34, name: '未完の幻想', iconUrl: '/images/artifacts/unfinished-reverie-icon.png', rarity: 5 },
    { id: 35, name: '黒曜の記録', iconUrl: '/images/artifacts/obsidian-codex-icon.png', rarity: 5 },
    { id: 36, name: '燼城の勇者の書', iconUrl: '/images/artifacts/scroll-hero-cinder-icon.png', rarity: 5 },
    { id: 37, name: '深層秘境の長夜', iconUrl: '/images/artifacts/finale-deep-galleries-icon.png', rarity: 5 },
    { id: 38, name: '永夜の誓約', iconUrl: '/images/artifacts/long-night-oath-icon.png', rarity: 5 },
    
    // 4星聖遺物セット
    { id: 39, name: '狂戦士', iconUrl: '/images/artifacts/berserker-icon.png', rarity: 4 },
    { id: 40, name: '勇者の心', iconUrl: '/images/artifacts/brave-heart-icon.png', rarity: 4 },
    { id: 41, name: '守護の心', iconUrl: '/images/artifacts/defender-will-icon.png', rarity: 4 },
    { id: 42, name: '博徒', iconUrl: '/images/artifacts/gambler-icon.png', rarity: 4 },
    { id: 43, name: '教官', iconUrl: '/images/artifacts/instructor-icon.png', rarity: 4 },
    { id: 44, name: '武人', iconUrl: '/images/artifacts/martial-artist-icon.png', rarity: 4 },
    { id: 45, name: '流浪する大地', iconUrl: '/images/artifacts/resolution-sojourner-icon.png', rarity: 4 },
    { id: 46, name: '学者', iconUrl: '/images/artifacts/scholar-icon.png', rarity: 4 },
    { id: 47, name: '亡命者', iconUrl: '/images/artifacts/exile-icon.png', rarity: 4 },
    { id: 48, name: '小さな奇跡', iconUrl: '/images/artifacts/tiny-miracle-icon.png', rarity: 4 },
    
    // 3星聖遺物セット
    { id: 49, name: '冒険者', iconUrl: '/images/artifacts/adventurer-icon.png', rarity: 3 },
    { id: 50, name: '幸運', iconUrl: '/images/artifacts/lucky-dog-icon.png', rarity: 3 },
    { id: 51, name: '旅医', iconUrl: '/images/artifacts/traveling-doctor-icon.png', rarity: 3 },
];
