export type character = {
    id: number,
    name: string,
    iconUrl: string
};

export const charlist: character[] = [
    // 炎元素
    { id: 1, name: 'アンバー', iconUrl: '/images/characters/amber-icon.png' },
    { id: 2, name: '香菱', iconUrl: '/images/characters/xiangling-icon.png' },
    { id: 3, name: 'ベネット', iconUrl: '/images/characters/bennett-icon.png' },
    { id: 4, name: '辛炎', iconUrl: '/images/characters/xinyan-icon.png' },
    { id: 5, name: 'ディルック', iconUrl: '/images/characters/diluc-icon.png' },
    { id: 6, name: 'クレー', iconUrl: '/images/characters/klee-icon.png' },
    { id: 7, name: '胡桃', iconUrl: '/images/characters/hutao-icon.png' },
    { id: 8, name: '宵宮', iconUrl: '/images/characters/yoimiya-icon.png' },
    { id: 9, name: '煙緋', iconUrl: '/images/characters/yanfei-icon.png' },
    { id: 10, name: 'トーマ', iconUrl: '/images/characters/thoma-icon.png' },
    { id: 11, name: 'デヒヤ', iconUrl: '/images/characters/dehya-icon.png' },
    { id: 12, name: 'リネ', iconUrl: '/images/characters/lyney-icon.png' },
    { id: 13, name: 'シュヴルーズ', iconUrl: '/images/characters/chevreuse-icon.png' },
    { id: 14, name: 'ゲーミング', iconUrl: '/images/characters/gaming-icon.png' },
    { id: 15, name: 'アルレッキーノ', iconUrl: '/images/characters/arlecchino-icon.png' },
    { id: 16, name: 'マヴィカ', iconUrl: '/images/characters/mavuika-icon.png' },
    
    // 水元素
    { id: 17, name: 'バーバラ', iconUrl: '/images/characters/barbara-icon.png' },
    { id: 18, name: '行秋', iconUrl: '/images/characters/xingqiu-icon.png' },
    { id: 19, name: 'モナ', iconUrl: '/images/characters/mona-icon.png' },
    { id: 20, name: 'タルタリヤ', iconUrl: '/images/characters/tartaglia-icon.png' },
    { id: 21, name: '神里綾人', iconUrl: '/images/characters/ayato-icon.png' },
    { id: 22, name: '夜蘭', iconUrl: '/images/characters/yelan-icon.png' },
    { id: 23, name: '珊瑚宮心海', iconUrl: '/images/characters/kokomi-icon.png' },
    { id: 24, name: 'ニィロウ', iconUrl: '/images/characters/nilou-icon.png' },
    { id: 25, name: 'キャンディス', iconUrl: '/images/characters/candace-icon.png' },
    { id: 26, name: 'ヌヴィレット', iconUrl: '/images/characters/neuvillette-icon.png' },
    { id: 27, name: 'フリーナ', iconUrl: '/images/characters/furina-icon.png' },
    { id: 28, name: 'シグウィン', iconUrl: '/images/characters/sigewinne-icon.png' },
    { id: 29, name: 'ムアラニ', iconUrl: '/images/characters/mualani-icon.png' },
    { id: 30, name: 'ミズキ', iconUrl: '/images/characters/mizuki-icon.png' },
    
    // 氷元素
    { id: 31, name: 'ガイア', iconUrl: '/images/characters/kaeya-icon.png' },
    { id: 32, name: '重雲', iconUrl: '/images/characters/chongyun-icon.png' },
    { id: 33, name: 'ディオナ', iconUrl: '/images/characters/diona-icon.png' },
    { id: 34, name: 'ロサリア', iconUrl: '/images/characters/rosaria-icon.png' },
    { id: 35, name: '七七', iconUrl: '/images/characters/qiqi-icon.png' },
    { id: 36, name: '甘雨', iconUrl: '/images/characters/ganyu-icon.png' },
    { id: 37, name: '神里綾華', iconUrl: '/images/characters/ayaka-icon.png' },
    { id: 38, name: 'エウルア', iconUrl: '/images/characters/eula-icon.png' },
    { id: 39, name: 'アーロイ', iconUrl: '/images/characters/aloy-icon.png' },
    { id: 40, name: '申鶴', iconUrl: '/images/characters/shenhe-icon.png' },
    { id: 41, name: 'レイラ', iconUrl: '/images/characters/layla-icon.png' },
    { id: 42, name: 'フレミネ', iconUrl: '/images/characters/freminet-icon.png' },
    { id: 43, name: 'ミカ', iconUrl: '/images/characters/mika-icon.png' },
    { id: 44, name: 'シャルロット', iconUrl: '/images/characters/charlotte-icon.png' },
    { id: 45, name: 'リオセスリ', iconUrl: '/images/characters/wriothesley-icon.png' },
    { id: 46, name: 'シトリリ', iconUrl: '/images/characters/citlali-icon.png' },
    
    // 雷元素
    { id: 47, name: 'リサ', iconUrl: '/images/characters/lisa-icon.png' },
    { id: 48, name: 'レザー', iconUrl: '/images/characters/razor-icon.png' },
    { id: 49, name: 'フィッシュル', iconUrl: '/images/characters/fischl-icon.png' },
    { id: 50, name: '北斗', iconUrl: '/images/characters/beidou-icon.png' },
    { id: 51, name: '刻晴', iconUrl: '/images/characters/keqing-icon.png' },
    { id: 52, name: '雷電将軍', iconUrl: '/images/characters/raiden-shogun-icon.png' },
    { id: 53, name: '九条裟羅', iconUrl: '/images/characters/sara-icon.png' },
    { id: 54, name: '八重神子', iconUrl: '/images/characters/yae-icon.png' },
    { id: 55, name: 'ドリー', iconUrl: '/images/characters/dori-icon.png' },
    { id: 56, name: 'セノ', iconUrl: '/images/characters/cyno-icon.png' },
    { id: 57, name: '久岐忍', iconUrl: '/images/characters/kuki-shinobu-icon.png' },
    { id: 58, name: 'クロリンデ', iconUrl: '/images/characters/clorinde-icon.png' },
    { id: 59, name: 'セトス', iconUrl: '/images/characters/setos-icon.png' },
    { id: 60, name: 'オロルン', iconUrl: '/images/characters/olorun-icon.png' },
    
    // 風元素
    { id: 61, name: 'ジン', iconUrl: '/images/characters/jean-icon.png' },
    { id: 62, name: 'ウェンティ', iconUrl: '/images/characters/venti-icon.png' },
    { id: 63, name: 'スクロース', iconUrl: '/images/characters/sucrose-icon.png' },
    { id: 64, name: '魈', iconUrl: '/images/characters/xiao-icon.png' },
    { id: 65, name: '楓原万葉', iconUrl: '/images/characters/kazuha-icon.png' },
    { id: 66, name: '鹿野院平蔵', iconUrl: '/images/characters/heizou-icon.png' },
    { id: 67, name: 'ファルザン', iconUrl: '/images/characters/faruzan-icon.png' },
    { id: 68, name: '早柚', iconUrl: '/images/characters/sayu-icon.png' },
    { id: 69, name: '放浪者', iconUrl: '/images/characters/wanderer-icon.png' },
    { id: 70, name: 'リネット', iconUrl: '/images/characters/lynette-icon.png' },
    { id: 71, name: '閑雲', iconUrl: '/images/characters/xianyun-icon.png' },
    { id: 72, name: 'チャスカ', iconUrl: '/images/characters/chasca-icon.png' },
    { id: 73, name: 'ランヤン', iconUrl: '/images/characters/lanyan-icon.png' },
    
    // 岩元素
    { id: 74, name: 'ノエル', iconUrl: '/images/characters/noelle-icon.png' },
    { id: 75, name: '凝光', iconUrl: '/images/characters/ningguang-icon.png' },
    { id: 76, name: '鍾離', iconUrl: '/images/characters/zhongli-icon.png' },
    { id: 77, name: 'アルベド', iconUrl: '/images/characters/albedo-icon.png' },
    { id: 78, name: '荒瀧一斗', iconUrl: '/images/characters/itto-icon.png' },
    { id: 79, name: '五郎', iconUrl: '/images/characters/gorou-icon.png' },
    { id: 80, name: '雲菫', iconUrl: '/images/characters/yunjin-icon.png' },
    { id: 81, name: 'ナヴィア', iconUrl: '/images/characters/navia-icon.png' },
    { id: 82, name: '千織', iconUrl: '/images/characters/chiori-icon.png' },
    { id: 83, name: 'カチーナ', iconUrl: '/images/characters/kachina-icon.png' },
    { id: 84, name: 'シローネン', iconUrl: '/images/characters/xilonen-icon.png' },
    
    // 草元素
    { id: 85, name: 'ティナリ', iconUrl: '/images/characters/tighnari-icon.png' },
    { id: 86, name: 'コレイ', iconUrl: '/images/characters/collei-icon.png' },
    { id: 87, name: 'ナヒーダ', iconUrl: '/images/characters/nahida-icon.png' },
    { id: 88, name: 'アルハイゼン', iconUrl: '/images/characters/alhaitham-icon.png' },
    { id: 89, name: 'ヨォーヨ', iconUrl: '/images/characters/yaoyao-icon.png' },
    { id: 90, name: '白朮', iconUrl: '/images/characters/baizhu-icon.png' },
    { id: 91, name: 'カーヴェ', iconUrl: '/images/characters/kaveh-icon.png' },
    { id: 92, name: 'キララ', iconUrl: '/images/characters/kirara-icon.png' },
    { id: 93, name: 'エミリー', iconUrl: '/images/characters/emilie-icon.png' },
    { id: 94, name: 'キニチ', iconUrl: '/images/characters/kinichi-icon.png' },
    
    // 主人公
    { id: 95, name: '空 (風)', iconUrl: '/images/characters/aether-anemo-icon.png' },
    { id: 96, name: '空', iconUrl: '/images/characters/aether-icon.png' },
    { id: 97, name: '蛍', iconUrl: '/images/characters/lumine-icon.png' },
];